# Generated by Django 6.0.3 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('ratingLabel', models.CharField(blank=True, max_length=100)),
                ('reviews', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, default='wedrowki', max_length=100)),
                ('ranking_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
