# Generated by Django 6.0.3 on 2026-06-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.offer'),
        ),
    ]
