# Generated by Django 6.0.3 on 2026-06-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guests_booking_room_type_booking_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Autor')),
                ('rating', models.FloatField(verbose_name='Ocena')),
                ('body', models.TextField(verbose_name='Treść opinii')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.offer')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
            },
        ),
    ]
