# Generated by Django 6.0.3 on 2026-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
