# Generated by Django 6.0.3 on 2026-06-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_offer_image_alter_offer_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywna'),
        ),
    ]
