# Generated by Django 6.0.3 on 2026-06-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_offer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bookings.offer')),
            ],
            options={
                'verbose_name': 'Blokada terminu',
                'verbose_name_plural': 'Blokady terminów',
                'ordering': ['start_date'],
            },
        ),
    ]
