# Generated by Django 6.0.3 on 2026-06-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cena bazowa (legacy)'),
        ),
    ]
